import type { APIRoute } from "astro";
import { getUserWithApproval } from "../../../lib/auth";
import {
  getSquaresLockedSetting,
  setSquaresLockedSetting,
  setMaxSquaresPerUserSetting,
} from "../../../lib/settings";
import {
  generateAxisNumbers,
  setScore,
  clearAllSquares,
  clearAllScores,
} from "../../../lib/squares";
import { logger } from "../../../lib/logger";

const log = logger.scope("SQUARES-ADMIN");

export const POST: APIRoute = async ({ request, redirect }) => {
  // Verify authentication, approval, and admin status
  const auth = await getUserWithApproval(request);
  if (!auth) {
    log.warn("Unauthenticated squares admin request");
    return redirect("/login", 302);
  }
  if (!auth.isApproved) {
    log.warn("Unapproved user tried to access squares admin:", auth.user.email);
    return redirect("/unauthorized", 302);
  }
  if (!auth.isAdmin) {
    log.warn("Non-admin user tried to access squares admin:", auth.user.email);
    return new Response(null, { status: 404 });
  }

  // Parse form data
  const formData = await request.formData();
  const action = formData.get("action")?.toString();
  const returnTo = formData.get("return_to")?.toString() || "/squares/admin";

  if (action === "toggle_squares_locked") {
    const currentValue = await getSquaresLockedSetting();
    const newValue = !currentValue;

    // If locking the game, generate new random numbers
    if (newValue) {
      await generateAxisNumbers();
      log.info("New axis numbers generated by:", auth.user.email);
    }

    await setSquaresLockedSetting(newValue);
    log.info("squares_locked toggled to:", newValue, "by:", auth.user.email);
    return redirect(returnTo, 302);
  }

  if (action === "set_max_squares") {
    const maxSquares = parseInt(formData.get("max_squares")?.toString() || "5", 10);
    if (maxSquares > 0 && maxSquares <= 100) {
      await setMaxSquaresPerUserSetting(maxSquares);
      log.info("max_squares_per_user set to:", maxSquares, "by:", auth.user.email);
    }
    return redirect(returnTo, 302);
  }

  if (action === "set_score") {
    const quarter = parseInt(formData.get("quarter")?.toString() || "0", 10);
    const seahawksScoreStr = formData.get("seahawks_score")?.toString();
    const patriotsScoreStr = formData.get("patriots_score")?.toString();

    if (quarter >= 1 && quarter <= 4) {
      const seahawksScore = seahawksScoreStr ? parseInt(seahawksScoreStr, 10) : null;
      const patriotsScore = patriotsScoreStr ? parseInt(patriotsScoreStr, 10) : null;

      await setScore(quarter, seahawksScore, patriotsScore);
      log.info(
        `Q${quarter} score set: Seahawks ${seahawksScore}, Patriots ${patriotsScore}`,
        "by:",
        auth.user.email
      );
    }
    return redirect(returnTo, 302);
  }

  if (action === "clear_all_squares") {
    await clearAllSquares();
    log.info("All squares cleared by:", auth.user.email);
    return redirect(returnTo, 302);
  }

  if (action === "clear_all_scores") {
    await clearAllScores();
    log.info("All scores cleared by:", auth.user.email);
    return redirect(returnTo, 302);
  }

  if (action === "reset_game") {
    await Promise.all([
      clearAllSquares(),
      clearAllScores(),
      setSquaresLockedSetting(false),
    ]);
    log.info("Game reset by:", auth.user.email);
    return redirect(returnTo, 302);
  }

  log.warn("Unknown squares admin action:", action);
  return redirect(returnTo, 302);
};
